travis:
  secure:
    BINSTAR_TOKEN: V3EyxzLalFgEFyKjEj3kiuHMIIetkASPCwHuPbCimRA/YRkMDvSvG4l+ajLsnMvd2ZfBRrKH64sK+99uZfc6iuG/3qKp8lIcGRqX0gWwDQ0mmr/YFl04hx4uS3nR5pBpHO18HcyuLqcHeRNX/wUe5X+Z+CXJeiUhm0Hvul8pDfBk66UuD8wrf51Ws/ZuhnBktIXUwGxYg8kNjGT6PSTOPyzN3YajiuPenl3Tu75hIupBln8ZZjyKDxzWquChyTAIXjQ6n2r7ThqWVP1NGCQi9OwfueuhxZM4ZfMO3W997lHbp/wpF1Gvg8ZaIsz2DZ5B3eBB7pfSyqLsqhoWXLrOYfUnqxa/JRN3+TdayGQ/p1QP7wQi7Q5OfJAJ7CYrV80EOxe9BVADFQ3ocOPEAIzCNfp7cCnJF3e3iC0Y95Fvts2pnXcJg3/JRbGcFkj46sxZmZG4aZ/XVeRjDqCyHDGHYsGBkqkuWqYsS2Y1C2FK5W/duETj1uEIoY+1XRMx/ZSb9V9SEMa53f5XPlqGkewyd+RJdI1ivx0TIUHkFRhtqSg5Mf4P93wFWaMM/eghBEOizfUF5VTlQBjKXA+QFAkItfYJpBxwVyeoYxEYa6RGLSSd+rdJY8OtMuygDCZE4M9higO2fDZlFZWaSC1kd2mGAe+ZYT2PqTa3nJ7dR0MK1mw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
